parameters:
#    badcow_address.example.class: Badcow\AddressBundle\Example

services:
#    badcow_address.example:
#        class: %badcow_address.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
